-- MySQL Script generated by MySQL Workbench
-- Wed Jun 13 21:53:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbescola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbescola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbescola` DEFAULT CHARACTER SET latin1 ;
USE `dbescola` ;

-- -----------------------------------------------------
-- Table `dbescola`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbescola`.`aluno` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbescola`.`escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbescola`.`escola` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(60) NOT NULL,
  `datafundacao` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbescola`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbescola`.`curso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idescola` INT(11) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_IDESCOLA_IDCURSO`
    FOREIGN KEY (`idescola`)
    REFERENCES `dbescola`.`escola` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dbescola`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbescola`.`matricula` (
  `idcurso` INT(11) NOT NULL,
  `idaluno` INT(11) NOT NULL,
  `nota` INT NULL,
  PRIMARY KEY (`idcurso`, `idaluno`),
  CONSTRAINT `FK_IDALUNO`
    FOREIGN KEY (`idaluno`)
    REFERENCES `dbescola`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_IDCURSO`
    FOREIGN KEY (`idcurso`)
    REFERENCES `dbescola`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
